# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [1]:
import numpy as np

In [2]:
# Create and solve the relevant system of equations
A = np.matrix([[29, 41], [23, 41]])
B = np.matrix([490, 448])

# Take the inverse of Matrix A 
A_inv = np.linalg.inv(A)
A_inv

matrix([[ 0.16666667, -0.16666667],
        [-0.09349593,  0.11788618]])

In [3]:
print(B.shape)

(1, 2)


In [4]:
B = B.T
print(B.shape)
B

(2, 1)


matrix([[490],
        [448]])

In [5]:
X = A_inv.dot(B)
X

matrix([[7.],
        [7.]])

In [6]:
x = np.linalg.solve(A, B)
x

matrix([[7.],
        [7.]])

In [7]:
# Describe your result
# bag of coffee = $ 7.00
# bag of tea = $ 7.00

## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [8]:
# Create and solve the relevant system of equations
A2 = np.matrix([[12, 3], [8, 3]])
B2 = np.matrix([162, 122])


# Take the inverse of Matrix A 
A_inv = np.linalg.inv(A)
A_inv

B2 = B2.T

In [9]:
x2 = np.linalg.solve(A2, B2)
x2

matrix([[10.],
        [14.]])

In [10]:
# Describe your result
# Children's ticket = $ 10.00
# Adult's ticket = $ 14.00

## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [11]:
# Create and solve the relevant system of equations
A3 = np.matrix([[1, 1, 1], [.5, .75, 1.25], [-2, 1, 0]])
B3 = np.matrix([7, 5.25, 0])

A3_inv = np.linalg.inv(A3)
A3_inv

matrix([[ 0.71428571, -0.57142857, -0.28571429],
        [ 1.42857143, -1.14285714,  0.42857143],
        [-1.14285714,  1.71428571, -0.14285714]])

In [12]:
B3.shape

(1, 3)

In [13]:
B3 = B3.T
B3
print(B3.shape)

(3, 1)


In [14]:
X = A3_inv.dot(B3)
X

matrix([[2.],
        [4.],
        [1.]])

In [15]:
np.linalg.solve(A3, B3)

matrix([[2.],
        [4.],
        [1.]])

In [16]:
# Describe your result
# We will need:
# 2 onions
# 4 tomatoes
# 1 carrot
# for our soup.

## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom, and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [17]:
# Create and solve the relevant system of equations
A4 =np.matrix([[1, 1, 1], [.1, .2, .3], [2, 0, -1]])
B4 = np.matrix([1240, 276, 0])

A4_inv = np.linalg.inv(A4)
A4_inv

matrix([[ -2.,  10.,   1.],
        [  7., -30.,  -2.],
        [ -4.,  20.,   1.]])

In [18]:
B4.shape

(1, 3)

In [19]:
B4 = B4.T
print(B4.shape)

(3, 1)


In [20]:
X = A4_inv.dot(B4)
X

matrix([[280.],
        [400.],
        [560.]])

In [21]:
np.linalg.solve(A4, B4)

matrix([[280.],
        [400.],
        [560.]])

In [22]:
# Describe your result
# Each apartment's rent:
# 1 bedroom = $ 280
# 2 bedroom = $ 400
# 3 bedroom = $ 560

## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 